---

- name: "MY BANNER PLAYBOOK"
  hosts: SWITCHES
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Configure MOTD Banner"
      cisco.ios.ios_banner: 
        banner: motd
        text: | 
          *** THIS IS MY NEW BANNER ***
        state: present
      
      register: my_banner

    - debug: var=my_banner